CREATE TABLE diff_result (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '编号',
  user_name VARCHAR(20) NOT NULL DEFAULT '' COMMENT '用户名',
  diff_time TIMESTAMP NOT NULL DEFAULT NOW() COMMENT '对比时间',
  source_file VARCHAR(50) NOT NULL DEFAULT '' COMMENT '源文件',
  target_file VARCHAR(50) NOT NULL DEFAULT '' COMMENT '目标文件',
  result_file VARCHAR(50) NOT NULL DEFAULT '' COMMENT '对比结果'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='文件对比结果记录表';