CREATE TABLE UserInfo
(
  id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  name VARCHAR(20) DEFAULT '' NOT NULL,
  password VARCHAR(20) DEFAULT '' NOT NULL,
  sex TINYINT DEFAULT 0 NOT NULL,
  age TINYINT DEFAULT 0 NOT NULL,
  comment VARCHAR(50) DEFAULT '' NOT NULL,
  usable BOOLEAN DEFAULT FALSE  NOT NULL,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_edit_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  group_id TINYINT DEFAULT 0 NOT NULL
);
ALTER TABLE UserInfo ADD CONSTRAINT unique_name UNIQUE (name);