DROP TABLE IF EXISTS UserInfo;
CREATE TABLE UserInfo
(
  id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  name VARCHAR(20) DEFAULT '' NOT NULL,
  password VARCHAR(20) DEFAULT '' NOT NULL,
  sex TINYINT DEFAULT 0 NOT NULL,
  age TINYINT DEFAULT 0 NOT NULL,
  comment VARCHAR(50) DEFAULT '' NOT NULL,
  usable BOOLEAN DEFAULT TRUE NOT NULL,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_edit_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  group_id TINYINT DEFAULT 0 NOT NULL
);
ALTER TABLE UserInfo ADD CONSTRAINT unique_name UNIQUE (name);

INSERT INTO UserInfo (name, password, sex, age, comment, group_id, last_edit_time)
VALUES ('Lynn', '111', 0, 25, 'Lynn', 1, CURRENT_TIMESTAMP ),
('Fred', '222', 1, 26, 'Fred', 1, CURRENT_TIMESTAMP),
('中文', '333', 1, 22, '中文', 1, CURRENT_TIMESTAMP),
('test123', '000', 0, 0, 'test123', 1, CURRENT_TIMESTAMP)
